### ISSUE TITLE
希望增加自选清理选项

### ISSUE THREAD

**Issue by nkh0472** [DavidPisces/ReduceMIUI#2]
MIUI里以小米视频、音乐、阅读、浏览器为代表的一些app既无法卸载，还有可能推送垃圾信息、占用储存空间、徒增耗电。希望可以提供自选项以较友好的方式可选卸载/冻结这些app，具体实现或许可以是（Magisk安装时使用电源键选择/启动时读取储存分区的某一可选配置文件/控制台命令切换）中的一种或几种。

app列表包括但不限于以下：

名称 | 描述 | 位置
MiGalleryLockscreen | 小米画报 | /data/app/
partner-com.duokan.reader | 阅读 | /data/app/
VoiceTrigger | 语音唤醒 | /system/app/
MiuiVideo | 小米视频 | /system/priv-app/
NewHome | 小米内容中心 | /system/priv-app/
Music | 音乐 | /system/priv-app/

以下为收音机相关
FM | 收音机调频服务 | /system/app/
MiRadio | 收音机 | /system/app/

以下为gms相关
GooglePlayServicesUpdater | Google Play 服务更新程序 | /data/app/
ConfigUpdater | Google Config Updater | /system/priv-app/
GoogleExtServicesPrebuilt | Android Service Library | /system/priv-app/
GmsCore | Google Play 服务 | /system/product/priv-app/
GoogleOneTimeInitializer | Google One Time Init | /system/product/priv-app/
GoogleServicesFramework | Google 服务框架 | /system/product/priv-app/

希望为开发者提供参考。

**Comment by nkh0472** [comment]
除上述外，我还整理了部分已自行冻结的app，确认不会引起卡米等问题，这些app也可以加入到自选清理列表甚至默认清理列表中：

名称 | 描述 | 位置
aiasst_service | AI虚拟服务(智能电话助理支持组件) | /system/app/
Email | 电子邮箱 | /system/app/
GameCenter | 游戏中心 | /system/app/
Health | 小米健康 | /system/app/
HybridPlatform | 快应用服务框架 | /system/app/
MiDrive | 小米云盘 | /system/app/
Mipay | 小米钱包 | /system/app/
MiuiCompass | 指南针 | /system/app/
MiuiDriveMode | 驾车模式 | /system/app/
MiuiScreenRecorder | 屏幕录制 | /system/app/
MSA-Global | 小米国际版广告组件 | /system/app/
SmartTravel | 智能出行 | /system/app/
VirtualSim | 全球上网 | /system/app/
WMService | WMService | /system/app/
XMPass | 小米卡包 | /system/app/
CallLogBackup | 自带通话记录备份(与小米云同步无关，卸载无影响) | /system/priv-app/
Huanji | 小米换机 | /system/priv-app/
NewHome | 小米内容中心(类似于即刻/今日头条) | /system/priv-app/

**Comment by nkh0472** [comment]
下面是另一些确定不会引起卡米的app：
CertInstaller | 证书安装程序 | /system/app/
FrequentPhrase | 常用语 | /system/app/
GoogleCalendarSyncAdapter | Google日历同步 | /system/app/
GoogleContactsSyncAdapter | Google通信录同步 | /system/app/
GoogleExtShared |   | /system/app/
GoogleTTS | Google文字转语音引擎 | /system/app/
HybridAccessory | 快应用支持组件 | /system/app/
LiveWallpapersPicker | 动态壁纸支持组件 | /system/app/
mi_connect_service | 小米互联通讯服务(用途未知) | /system/app/
MiWallpaper |   | /system/app/
PaymentService | 米币支付 | /system/app/
Perfdump | 系统性能检测 | /system/app/
TouchAssistant | 悬浮球 | /system/app/
Userguide | 用户手册 | /system/app/
VipAccount | 小米社区 | /system/app/
VoiceAssist | 小爱同学 | /system/app/
CleanMaster | 垃圾清理 | /system/priv-app/
ContentExtension | 传送门 | /system/priv-app/
GoogleBackupTransport | Google备份传输 | /system/priv-app/
GoogleExtServices |   | /system/priv-app/
GoogleFeedback | 应用商店反馈代理程序 | /system/priv-app/
GoogleOneTimeInitializer |   | /system/priv-app/
GooglePartnerSetup | Google合作伙伴设置 | /system/priv-app/
GoogleServicesFramework | Google服务框架 | /system/priv-app/
MiShare | 小米互传(支持小米/OPPO/vivo/米本) | /system/priv-app/
MiuiScanner | 扫一扫 | /system/priv-app/
MiuiVideo | 小米视频 | /system/priv-app/
PersonalAssistant | 智能助理/负一屏 | /system/priv-app/
Phonesky | GooglePlay商店 | /system/priv-app/
PrebuiltGmsCorePi | GooglePlay服务 | /system/priv-app/
QuickSearchBox | 搜索 | /system/priv-app/

**Comment by DavidPisces** [comment]
在考虑范围内，有空就做做看吧

**Comment by Howard20181** [comment]
小米视频冻结或卸载后相册会异常，表现为功能缺失，比如手动旋转按钮丢失

**Comment by DavidPisces** [comment]
2.7已经支持包名精简了
